import java.io.*;
import java.util.*;

/**
 * EduWise Tracker
 * A console app that helps a student keep track of modules, deadlines and
 * grades, and can export the current record as an HTML report.
 *
 * Data is saved to modules.txt so your records persist between runs.
 */
public class EduWiseTracker {

    static final String DATA_FILE = "modules.txt";
    static List<Module> modules = new ArrayList<>();

    public static void main(String[] args) {
        loadModules();
        Scanner scanner = new Scanner(System.in);
        boolean running = true;

        System.out.println("=== EduWise Tracker ===");

        while (running) {
            System.out.println("\n1. Add a module");
            System.out.println("2. View all modules");
            System.out.println("3. Generate HTML report");
            System.out.println("4. Exit");
            System.out.print("Choose an option: ");

            String choice = scanner.nextLine().trim();

            switch (choice) {
                case "1":
                    addModule(scanner);
                    break;
                case "2":
                    viewModules();
                    break;
                case "3":
                    generateHtmlReport();
                    break;
                case "4":
                    running = false;
                    System.out.println("Goodbye!");
                    break;
                default:
                    System.out.println("Please choose 1, 2, 3 or 4.");
            }
        }
    }

    static void addModule(Scanner scanner) {
        System.out.print("Module name: ");
        String name = scanner.nextLine().trim();

        System.out.print("Deadline (e.g. 2026-11-20) or leave blank: ");
        String deadline = scanner.nextLine().trim();

        System.out.print("Current grade % (leave blank if not graded yet): ");
        String gradeInput = scanner.nextLine().trim();
        String grade = gradeInput.isEmpty() ? "-" : gradeInput;

        Module m = new Module(name, deadline.isEmpty() ? "-" : deadline, grade);
        modules.add(m);
        saveModules();
        System.out.println("Added \"" + name + "\".");
    }

    static void viewModules() {
        if (modules.isEmpty()) {
            System.out.println("No modules added yet.");
            return;
        }
        System.out.println("\n--- Your Modules ---");
        for (Module m : modules) {
            System.out.println(m.name + " | Deadline: " + m.deadline + " | Grade: " + m.grade);
        }
    }

    static void generateHtmlReport() {
        try (PrintWriter out = new PrintWriter(new FileWriter("report.html"))) {
            out.println("<!DOCTYPE html>");
            out.println("<html lang=\"en\"><head><meta charset=\"UTF-8\">");
            out.println("<title>EduWise Report</title>");
            out.println("<style>");
            out.println("body{font-family:Arial,sans-serif;background:#F3F5F7;color:#121620;padding:30px;}");
            out.println("h1{color:#10233F;} table{border-collapse:collapse;width:100%;max-width:600px;}");
            out.println("th,td{border:1px solid #DDE3E9;padding:10px;text-align:left;}");
            out.println("th{background:#10233F;color:#fff;}");
            out.println("</style></head><body>");
            out.println("<h1>EduWise Report</h1>");
            out.println("<p>Generated by EduWise Tracker (Java)</p>");

            if (modules.isEmpty()) {
                out.println("<p>No modules recorded yet.</p>");
            } else {
                out.println("<table><tr><th>Module</th><th>Deadline</th><th>Grade</th></tr>");
                for (Module m : modules) {
                    out.println("<tr><td>" + escape(m.name) + "</td><td>" + escape(m.deadline)
                            + "</td><td>" + escape(m.grade) + "</td></tr>");
                }
                out.println("</table>");
            }

            out.println("</body></html>");
            System.out.println("Report saved as report.html — open it in a browser to view it.");
        } catch (IOException e) {
            System.out.println("Could not write report: " + e.getMessage());
        }
    }

    static String escape(String s) {
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    static void saveModules() {
        try (PrintWriter out = new PrintWriter(new FileWriter(DATA_FILE))) {
            for (Module m : modules) {
                out.println(m.name + "|" + m.deadline + "|" + m.grade);
            }
        } catch (IOException e) {
            System.out.println("Could not save data: " + e.getMessage());
        }
    }

    static void loadModules() {
        File file = new File(DATA_FILE);
        if (!file.exists()) return;

        try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split("\\|", -1);
                if (parts.length == 3) {
                    modules.add(new Module(parts[0], parts[1], parts[2]));
                }
            }
        } catch (IOException e) {
            System.out.println("Could not load saved data: " + e.getMessage());
        }
    }

    static class Module {
        String name, deadline, grade;
        Module(String name, String deadline, String grade) {
            this.name = name;
            this.deadline = deadline;
            this.grade = grade;
        }
    }
}
